// import './man'
import './vim'
import './beta'
import './help'
import './start'
import './rules'
import './which'
import './source'
import './distro'
import './offtopic'
import './community'
import './documentation'
